"""empty message

Revision ID: 0993eb298bda
Revises: 94f0c85dd459
Create Date: 2023-08-16 00:30:42.278026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0993eb298bda'
down_revision = '94f0c85dd459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('photo', sa.Column('height', sa.Integer(), nullable=True))
    op.drop_column('purchase', 'height')
    op.drop_column('purchase', 'width')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('width', sa.INTEGER(), nullable=True))
    op.add_column('purchase', sa.Column('height', sa.INTEGER(), nullable=True))
    op.drop_column('photo', 'height')
    op.drop_column('photo', 'width')
    # ### end Alembic commands ###
