"""Added view count for each photo

Revision ID: 0b78404b1c9a
Revises: 27a9b86c3ada
Create Date: 2023-09-09 23:22:03.542762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b78404b1c9a'
down_revision = '27a9b86c3ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'views')
    # ### end Alembic commands ###
