"""Added subscribed bool for each user

Revision ID: 27a9b86c3ada
Revises: 0993eb298bda
Create Date: 2023-09-01 16:42:26.713523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a9b86c3ada'
down_revision = '0993eb298bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('subscribed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'subscribed')
    # ### end Alembic commands ###
