"""Added width and height attributes to Photo

Revision ID: 94f0c85dd459
Revises: b91be5ce260b
Create Date: 2023-08-14 23:04:28.400928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94f0c85dd459'
down_revision = 'b91be5ce260b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('purchase', sa.Column('height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase', 'height')
    op.drop_column('purchase', 'width')
    # ### end Alembic commands ###
