"""Added photo description

Revision ID: b91be5ce260b
Revises: ce234e3e4386
Create Date: 2023-08-12 23:03:51.361073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b91be5ce260b'
down_revision = 'ce234e3e4386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('description', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'description')
    # ### end Alembic commands ###
